#
# Makefile - global makefile defines
# Copyright (C) 2015-2016 Heiko Abraham
# All rights reserved.
#

# current working directory
CURRENT_DIR:=$(shell pwd)

ifeq ($(MAKEFILENAME),)
MAKEFILENAME := $(firstword $(MAKEFILE_LIST))
endif

#
# detect number of CPUs usable for make jobs
#
NUM_CPUS=$(shell sysctl -n hw.ncpu)
MJOBS=-j$(NUM_CPUS)

RM=/bin/rm
MKDIR=/bin/mkdir


#
# define source versions
#

CMAKE_VERSION_NO:=3.5.2
CMAKE_VERSION:=cmake-$(CMAKE_VERSION_NO)

LLVM_VERSION_NO:=3.9.1
LLVM_VERSION:=llvm-$(LLVM_VERSION_NO)
CLANG_VERSION:=cfe-$(LLVM_VERSION_NO)
COMPILER_RT_VERSION:=compiler-rt-$(LLVM_VERSION_NO)
LLDB_VERSION:=lldb-$(LLVM_VERSION_NO)
LLD_VERSION:=lld-$(LLVM_VERSION_NO)

#
# define project directories
#
DOWNLOAD_DIR:=../download-cache
BUILD_DIR:=$(CURRENT_DIR)/../builddir
PREFIX_HOST:=$(BUILD_DIR)/usr-host
TOOLCHAIN_BUNDLE_NAME:=llvm_$(LLVM_VERSION_NO).xctoolchain
PREFIX:=$(BUILD_DIR)/$(TOOLCHAIN_BUNDLE_NAME)/usr

#
# prepend own tools to path
#
PATH_EXT=PATH=$(PREFIX_HOST)/bin:$(PREFIX)/bin:$(PATH)



all: build


$(PREFIX)/:
	$(MKDIR) -p $(PREFIX)/

$(BUILD_DIR)/:
	$(MKDIR) -p $(BUILD_DIR)/
	# xattr -w com.apple.metadata:comapple_backupexcludeItem com.apple.backupd <filename>
	# com.apple.metadata:com_apple_backup_excludeItem
